import mongoose from "mongoose";
import Doctor from "./models/Doctor.js";
;
import { MONGO_URI } from "./config/env.js";


const dummyDoctors = [
  // --- Cardiology ---
  {
    name: "Dr. Sita Sharma",
    email: "sita.sharma1@gmail.com",
    phone: "9811000001",
    specialization: "Cardiologist",
    department: "Cardiology",
    experienceYears: 12,
    consultationFee: 2000,
    schedule: {
      workingDays: ["Mon", "Tue", "Thu"],
      workingHours: { start: "09:00", end: "16:00" },
      breakTime: { start: "12:30", end: "13:30" },
      appointmentDuration: 20,
    },
    bookedSlots: [],
    isActive: true,
  },
  {
    name: "Dr. Rajesh Thapa",
    email: "rajesh.thapa1@gmail.com",
    phone: "9811000002",
    specialization: "Cardiologist",
    department: "Cardiology",
    experienceYears: 15,
    consultationFee: 2500,
    schedule: {
      workingDays: ["Mon", "Wed", "Fri"],
      workingHours: { start: "10:00", end: "17:00" },
      breakTime: { start: "13:00", end: "14:00" },
      appointmentDuration: 30,
    },
    bookedSlots: [],
    isActive: true,
  },
  {
    name: "Dr. Meera Koirala",
    email: "meera.koirala1@gmail.com",
    phone: "9811000003",
    specialization: "Cardiologist",
    department: "Cardiology",
    experienceYears: 10,
    consultationFee: 1800,
    schedule: {
      workingDays: ["Tue", "Thu", "Sat"],
      workingHours: { start: "08:30", end: "14:30" },
      breakTime: { start: "11:00", end: "11:30" },
      appointmentDuration: 15,
    },
    bookedSlots: [],
    isActive: true,
  },
  {
    name: "Dr. Anil Gurung",
    email: "anil.gurung1@gmail.com",
    phone: "9811000004",
    specialization: "Cardiologist",
    department: "Cardiology",
    experienceYears: 20,
    consultationFee: 2200,
    schedule: {
      workingDays: ["Mon", "Wed", "Fri"],
      workingHours: { start: "09:00", end: "15:00" },
      breakTime: { start: "12:00", end: "12:30" },
      appointmentDuration: 25,
    },
    bookedSlots: [],
    isActive: true,
  },

  // --- Pulmonology ---
  {
    name: "Dr. Priya Basnet",
    email: "priya.basnet1@gmail.com",
    phone: "9811000011",
    specialization: "Pulmonologist",
    department: "Pulmonology",
    experienceYears: 10,
    consultationFee: 1800,
    schedule: {
      workingDays: ["Mon", "Tue", "Thu", "Sat"],
      workingHours: { start: "08:00", end: "15:00" },
      breakTime: { start: "11:30", end: "12:30" },
      appointmentDuration: 30,
    },
    bookedSlots: [],
    isActive: true,
  },
  {
    name: "Dr. Ramesh Thapa",
    email: "ramesh.thapa1@gmail.com",
    phone: "9811000012",
    specialization: "Pulmonologist",
    department: "Pulmonology",
    experienceYears: 15,
    consultationFee: 2000,
    schedule: {
      workingDays: ["Tue", "Wed", "Fri"],
      workingHours: { start: "09:30", end: "16:30" },
      breakTime: { start: "12:30", end: "13:30" },
      appointmentDuration: 20,
    },
    bookedSlots: [],
    isActive: true,
  },
  {
    name: "Dr. Sunita Shrestha",
    email: "sunita.shrestha1@gmail.com",
    phone: "9811000013",
    specialization: "Pulmonologist",
    department: "Pulmonology",
    experienceYears: 8,
    consultationFee: 1600,
    schedule: {
      workingDays: ["Mon", "Thu", "Sat"],
      workingHours: { start: "08:30", end: "14:30" },
      breakTime: { start: "11:00", end: "11:30" },
      appointmentDuration: 15,
    },
    bookedSlots: [],
    isActive: true,
  },
  {
    name: "Dr. Binod Lama",
    email: "binod.lama1@gmail.com",
    phone: "9811000014",
    specialization: "Pulmonologist",
    department: "Pulmonology",
    experienceYears: 12,
    consultationFee: 2100,
    schedule: {
      workingDays: ["Tue", "Thu", "Fri"],
      workingHours: { start: "09:00", end: "15:30" },
      breakTime: { start: "12:00", end: "12:30" },
      appointmentDuration: 25,
    },
    bookedSlots: [],
    isActive: true,
  },

  // --- Neurology ---
  {
    name: "Dr. Ramesh Thapa",
    email: "ramesh.thapa2@gmail.com",
    phone: "9811000021",
    specialization: "Neurologist",
    department: "Neurology",
    experienceYears: 15,
    consultationFee: 1800,
    schedule: {
      workingDays: ["Mon", "Tue", "Wed"],
      workingHours: { start: "08:30", end: "15:30" },
      breakTime: { start: "11:30", end: "12:30" },
      appointmentDuration: 30,
    },
    bookedSlots: [],
    isActive: true,
  },
  {
    name: "Dr. Anju Shrestha",
    email: "anju.shrestha1@gmail.com",
    phone: "9811000022",
    specialization: "Neurologist",
    department: "Neurology",
    experienceYears: 10,
    consultationFee: 1700,
    schedule: {
      workingDays: ["Tue", "Thu", "Sat"],
      workingHours: { start: "09:00", end: "15:00" },
      breakTime: { start: "12:00", end: "12:30" },
      appointmentDuration: 20,
    },
    bookedSlots: [],
    isActive: true,
  },
  {
    name: "Dr. Binod Koirala",
    email: "binod.koirala1@gmail.com",
    phone: "9811000023",
    specialization: "Neurologist",
    department: "Neurology",
    experienceYears: 20,
    consultationFee: 2200,
    schedule: {
      workingDays: ["Mon", "Wed", "Fri"],
      workingHours: { start: "09:00", end: "16:00" },
      breakTime: { start: "12:30", end: "13:30" },
      appointmentDuration: 25,
    },
    bookedSlots: [],
    isActive: true,
  },
  {
    name: "Dr. Meera Bhattarai",
    email: "meera.bhattarai1@gmail.com",
    phone: "9811000024",
    specialization: "Neurologist",
    department: "Neurology",
    experienceYears: 12,
    consultationFee: 1900,
    schedule: {
      workingDays: ["Tue", "Thu", "Fri"],
      workingHours: { start: "08:30", end: "15:30" },
      breakTime: { start: "11:30", end: "12:30" },
      appointmentDuration: 30,
    },
    bookedSlots: [],
    isActive: true,
  },

  // --- General Medicine ---
  {
    name: "Dr. Suman KC",
    email: "suman.kc1@gmail.com",
    phone: "9811000031",
    specialization: "General Physician",
    department: "General Medicine",
    experienceYears: 14,
    consultationFee: 1500,
    schedule: {
      workingDays: ["Mon", "Tue", "Wed"],
      workingHours: { start: "09:00", end: "16:00" },
      breakTime: { start: "12:00", end: "12:30" },
      appointmentDuration: 25,
    },
    bookedSlots: [],
    isActive: true,
  },
  {
    name: "Dr. Anita Shrestha",
    email: "anita.shrestha1@gmail.com",
    phone: "9811000032",
    specialization: "General Physician",
    department: "General Medicine",
    experienceYears: 10,
    consultationFee: 1400,
    schedule: {
      workingDays: ["Tue", "Thu", "Fri"],
      workingHours: { start: "08:30", end: "15:30" },
      breakTime: { start: "11:30", end: "12:00" },
      appointmentDuration: 20,
    },
    bookedSlots: [],
    isActive: true,
  },
  {
    name: "Dr. Bikash Thapa",
    email: "bikash.thapa1@gmail.com",
    phone: "9811000033",
    specialization: "General Physician",
    department: "General Medicine",
    experienceYears: 18,
    consultationFee: 1600,
    schedule: {
      workingDays: ["Mon", "Wed", "Fri"],
      workingHours: { start: "09:30", end: "16:30" },
      breakTime: { start: "12:30", end: "13:00" },
      appointmentDuration: 30,
    },
    bookedSlots: [],
    isActive: true,
  },
  {
    name: "Dr. Meera KC",
    email: "meera.kc1@gmail.com",
    phone: "9811000034",
    specialization: "General Physician",
    department: "General Medicine",
    experienceYears: 12,
    consultationFee: 1500,
    schedule: {
      workingDays: ["Tue", "Thu", "Sat"],
      workingHours: { start: "08:30", end: "14:30" },
      breakTime: { start: "11:00", end: "11:30" },
      appointmentDuration: 20,
    },
    bookedSlots: [],
    isActive: true,
  },

  // --- Orthopedics ---
  {
    name: "Dr. Anil Rai",
    email: "anil.rai1@gmail.com",
    phone: "9811000041",
    specialization: "Orthopedic Surgeon",
    department: "Orthopedics",
    experienceYears: 15,
    consultationFee: 2000,
    schedule: {
      workingDays: ["Mon", "Wed", "Fri"],
      workingHours: { start: "09:00", end: "16:00" },
      breakTime: { start: "12:00", end: "12:30" },
      appointmentDuration: 30,
    },
    bookedSlots: [],
    isActive: true,
  },
  {
    name: "Dr. Sunita Lama",
    email: "sunita.lama1@gmail.com",
    phone: "9811000042",
    specialization: "Orthopedic Surgeon",
    department: "Orthopedics",
    experienceYears: 12,
    consultationFee: 1800,
    schedule: {
      workingDays: ["Tue", "Thu", "Sat"],
      workingHours: { start: "08:30", end: "14:30" },
      breakTime: { start: "11:00", end: "11:30" },
      appointmentDuration: 25,
    },
    bookedSlots: [],
    isActive: true,
  },
  {
    name: "Dr. Ramesh KC",
    email: "ramesh.kc1@gmail.com",
    phone: "9811000043",
    specialization: "Orthopedic Surgeon",
    department: "Orthopedics",
    experienceYears: 20,
    consultationFee: 2200,
    schedule: {
      workingDays: ["Mon", "Tue", "Thu"],
      workingHours: { start: "09:30", end: "16:30" },
      breakTime: { start: "12:30", end: "13:00" },
      appointmentDuration: 30,
    },
    bookedSlots: [],
    isActive: true,
  },
  {
    name: "Dr. Anita Gurung",
    email: "anita.gurung1@gmail.com",
    phone: "9811000044",
    specialization: "Orthopedic Surgeon",
    department: "Orthopedics",
    experienceYears: 10,
    consultationFee: 1700,
    schedule: {
      workingDays: ["Wed", "Fri", "Sat"],
      workingHours: { start: "08:30", end: "15:00" },
      breakTime: { start: "11:30", end: "12:00" },
      appointmentDuration: 20,
    },
    bookedSlots: [],
    isActive: true,
  },

  // --- Emergency ---
  {
    name: "Dr. Binod Shrestha",
    email: "binod.shrestha1@gmail.com",
    phone: "9811000051",
    specialization: "Emergency Physician",
    department: "Emergency",
    experienceYears: 18,
    consultationFee: 2000,
    schedule: {
      workingDays: ["Mon", "Tue", "Wed"],
      workingHours: { start: "08:00", end: "16:00" },
      breakTime: { start: "12:00", end: "12:30" },
      appointmentDuration: 20,
    },
    bookedSlots: [],
    isActive: true,
  },
  {
    name: "Dr. Sunita KC",
    email: "sunita.kc1@gmail.com",
    phone: "9811000052",
    specialization: "Emergency Physician",
    department: "Emergency",
    experienceYears: 12,
    consultationFee: 1800,
    schedule: {
      workingDays: ["Thu", "Fri", "Sat"],
      workingHours: { start: "09:00", end: "17:00" },
      breakTime: { start: "12:30", end: "13:00" },
      appointmentDuration: 25,
    },
    bookedSlots: [],
    isActive: true,
  },
  {
    name: "Dr. Ramesh Gurung",
    email: "ramesh.gurung1@gmail.com",
    phone: "9811000053",
    specialization: "Emergency Physician",
    department: "Emergency",
    experienceYears: 15,
    consultationFee: 2000,
    schedule: {
      workingDays: ["Mon", "Wed", "Fri"],
      workingHours: { start: "08:30", end: "15:30" },
      breakTime: { start: "11:30", end: "12:00" },
      appointmentDuration: 30,
    },
    bookedSlots: [],
    isActive: true,
  },
  {
    name: "Dr. Meera Lama",
    email: "meera.lama1@gmail.com",
    phone: "9811000054",
    specialization: "Emergency Physician",
    department: "Emergency",
    experienceYears: 10,
    consultationFee: 1700,
    schedule: {
      workingDays: ["Tue", "Thu", "Sat"],
      workingHours: { start: "08:00", end: "14:00" },
      breakTime: { start: "11:00", end: "11:30" },
      appointmentDuration: 20,
    },
    bookedSlots: [],
    isActive: true,
  },

  // --- Ophthalmology ---
  {
    name: "Dr. Sita KC",
    email: "sita.kc1@gmail.com",
    phone: "9811000061",
    specialization: "Ophthalmologist",
    department: "Ophthalmology",
    experienceYears: 12,
    consultationFee: 1800,
    schedule: {
      workingDays: ["Mon", "Wed", "Fri"],
      workingHours: { start: "09:00", end: "16:00" },
      breakTime: { start: "12:00", end: "12:30" },
      appointmentDuration: 25,
    },
    bookedSlots: [],
    isActive: true,
  },
  {
    name: "Dr. Rajesh Lama",
    email: "rajesh.lama1@gmail.com",
    phone: "9811000062",
    specialization: "Ophthalmologist",
    department: "Ophthalmology",
    experienceYears: 15,
    consultationFee: 2000,
    schedule: {
      workingDays: ["Tue", "Thu", "Sat"],
      workingHours: { start: "08:30", end: "15:30" },
      breakTime: { start: "11:30", end: "12:00" },
      appointmentDuration: 30,
    },
    bookedSlots: [],
    isActive: true,
  },
  {
    name: "Dr. Anju KC",
    email: "anju.kc1@gmail.com",
    phone: "9811000063",
    specialization: "Ophthalmologist",
    department: "Ophthalmology",
    experienceYears: 10,
    consultationFee: 1700,
    schedule: {
      workingDays: ["Mon", "Tue", "Thu"],
      workingHours: { start: "08:00", end: "14:30" },
      breakTime: { start: "11:00", end: "11:30" },
      appointmentDuration: 20,
    },
    bookedSlots: [],
    isActive: true,
  },
  {
    name: "Dr. Binod Shrestha",
    email: "binod.shrestha2@gmail.com",
    phone: "9811000064",
    specialization: "Ophthalmologist",
    department: "Ophthalmology",
    experienceYears: 18,
    consultationFee: 2200,
    schedule: {
      workingDays: ["Wed", "Fri", "Sat"],
      workingHours: { start: "09:30", end: "16:30" },
      breakTime: { start: "12:30", end: "13:00" },
      appointmentDuration: 25,
    },
    bookedSlots: [],
    isActive: true,
  },

  // --- Dermatology ---
  {
    name: "Dr. Meera Sharma",
    email: "meera.sharma1@gmail.com",
    phone: "9811000071",
    specialization: "Dermatologist",
    department: "Dermatology",
    experienceYears: 12,
    consultationFee: 1600,
    schedule: {
      workingDays: ["Mon", "Wed", "Fri"],
      workingHours: { start: "09:00", end: "15:30" },
      breakTime: { start: "12:00", end: "12:30" },
      appointmentDuration: 20,
    },
    bookedSlots: [],
    isActive: true,
  },
  {
    name: "Dr. Rajesh KC",
    email: "rajesh.kc2@gmail.com",
    phone: "9811000072",
    specialization: "Dermatologist",
    department: "Dermatology",
    experienceYears: 15,
    consultationFee: 2000,
    schedule: {
      workingDays: ["Tue", "Thu", "Sat"],
      workingHours: { start: "08:30", end: "15:30" },
      breakTime: { start: "11:30", end: "12:00" },
      appointmentDuration: 25,
    },
    bookedSlots: [],
    isActive: true,
  },
  {
    name: "Dr. Anju Lama",
    email: "anju.lama1@gmail.com",
    phone: "9811000073",
    specialization: "Dermatologist",
    department: "Dermatology",
    experienceYears: 10,
    consultationFee: 1700,
    schedule: {
      workingDays: ["Mon", "Tue", "Thu"],
      workingHours: { start: "08:00", end: "14:30" },
      breakTime: { start: "11:00", end: "11:30" },
      appointmentDuration: 20,
    },
    bookedSlots: [],
    isActive: true,
  },
  {
    name: "Dr. Binod Sharma",
    email: "binod.sharma1@gmail.com",
    phone: "9811000074",
    specialization: "Dermatologist",
    department: "Dermatology",
    experienceYears: 18,
    consultationFee: 2200,
    schedule: {
      workingDays: ["Wed", "Fri", "Sat"],
      workingHours: { start: "09:30", end: "16:30" },
      breakTime: { start: "12:30", end: "13:00" },
      appointmentDuration: 25,
    },
    bookedSlots: [],
    isActive: true,
  },

  // --- Dentistry ---
  {
    name: "Dr. Sita Basnet",
    email: "sita.basnet1@gmail.com",
    phone: "9811000081",
    specialization: "Dentist",
    department: "Dentistry",
    experienceYears: 12,
    consultationFee: 1500,
    schedule: {
      workingDays: ["Mon", "Wed", "Fri"],
      workingHours: { start: "09:00", end: "15:00" },
      breakTime: { start: "12:00", end: "12:30" },
      appointmentDuration: 20,
    },
    bookedSlots: [],
    isActive: true,
  },
  {
    name: "Dr. Rajesh KC",
    email: "rajesh.kc3@gmail.com",
    phone: "9811000082",
    specialization: "Dentist",
    department: "Dentistry",
    experienceYears: 15,
    consultationFee: 2000,
    schedule: {
      workingDays: ["Tue", "Thu", "Sat"],
      workingHours: { start: "08:30", end: "14:30" },
      breakTime: { start: "11:00", end: "11:30" },
      appointmentDuration: 25,
    },
    bookedSlots: [],
    isActive: true,
  },
];

const seedDoctors = async () => {
  try {
    
  const connectDB = async () => {
      try {
        console.log(MONGO_URI)
        await mongoose.connect("mongodb://localhost:27017/MediPal");
        console.log("MongoDB connected successfully");
      } catch (error) {
        console.error("MongoDB connection error:", error);
        process.exit(1);
      }
    }
     await connectDB();
    await Doctor.insertMany(dummyDoctors);
    console.log("Doctors seeded successfully ✅");
    process.exit(0);
    
  } catch (error) {
    console.error("Seeding error ❌", error);
    process.exit(1);
  }
};

seedDoctors();
